### ISSUE TITLE
0.1.0 Todo

### ISSUE THREAD

**Issue by sairion** [sairion/ajaxo#1]
## Productivity
- [ ] Improve test coverage
- [ ] Complete Webpack build script
- [ ] Complete Release script
## Ajaxo Internal
- [ ] `jQuery.ajax` -> `window.fetch`
- [ ] lodash deps
  - [ ] `_.extend` -> `object-assign`
  - [ ] typechecks -> `is` module
  - [ ] `_.template` separate module
